### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by dennis-every** [dennis-every/recipes-app#11]
Hello World!

This is the Kanban board setup for the recipes-app project between 2 collaborators: @ashmalzahra and @dennis-every.

https://github.com/users/dennis-every/projects/2/views/1

**Comment by addod19** [comment]
### Hi @dennis-every and @ashmalzahra, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- [ ] All cards are assigned members :rocket: 
- [ ] Title, number of points and description present :fireworks: 


## Required Changes ♻️
_Check the comments under the review._
- [ ] The points difference between the 2 collaborators should not be greater or equal to 5pts, however, here is how the points are distributed 12pts and 7pts and the difference between them is 5pts, let us ensure the points are distributed in a fair manner. Let us kindly fix it
![Screenshot from 2023-05-22 19-41-00](https://github.com/dennis-every/recipes-app/assets/46388113/9dbf1e5e-2ea8-4ece-82f6-b92a4257447a)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OyePriscilla** [comment]
Hi @dennis-every  and @ashmalzahra 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Tasks assigned to group members fairly ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
